---
labels:
  platform: linux/amd64
  backend: docker

when:
  event:
    - tag
    - push

depends_on:
  - windows-build-and-push

skip_clone: true

matrix:
  include:
    - image: woodpecker-agent
      version: 2.7.3
    - image: woodpecker-agent
      version: 2.6.0
    - image: woodpecker-git-plugin
      version: latest
    - image: woodpecker-windows-base
      version: latest

steps:
  - name: Add 'docker-hub' label
    image: registry.geco-it.net/${CI_REPO_OWNER,,}/woodpecker-harbor-label-plugin
    settings:
      DOCKER_REGISTRY:
        from_secret: DOCKER_REGISTRY
      DOCKER_USERNAME:
        from_secret: DOCKER_REGISTRY_USERNAME
      DOCKER_PASSWORD:
        from_secret: DOCKER_REGISTRY_PASSWORD
      debug: true
      label: docker-hub
      project: ${CI_REPO_OWNER,,}
      image: ${image}
      tag: ${version}
