---
labels:
  platform: windows/amd64
  backend: local

depends_on:
  - windows-build-and-push-base

matrix:
  plugin:
    - git

steps:
  - name: configure environment
    image: bash.exe
    environment:
      DOCKER_REGISTRY:
        from_secret: DOCKER_REGISTRY
    commands:
      - cd ./build
      - cp .env.sample .env
      - sed -e "s;^DOCKER_REGISTRY=.*;DOCKER_REGISTRY=$${DOCKER_REGISTRY};" -i .env
    when:
      event: push

  - name: build docker ${plugin}-plugin
    image: bash.exe
    commands:
      - cd ./build
      - docker-compose build plugin-${plugin}
    when:
      event: push

  - name: configure environment
    image: bash.exe
    environment:
      DOCKER_REGISTRY:
        from_secret: DOCKER_REGISTRY
      DOCKER_REGISTRY_USERNAME:
        from_secret: DOCKER_REGISTRY_USERNAME
      DOCKER_REGISTRY_PASSWORD:
        from_secret: DOCKER_REGISTRY_PASSWORD
    commands:
      - cd ./build
      - cp .env.sample .env
      - sed -e "s;^DOCKER_REGISTRY=.*;DOCKER_REGISTRY=$${DOCKER_REGISTRY};" -i .env
      - echo "$${DOCKER_REGISTRY_PASSWORD}" | docker login $${DOCKER_REGISTRY} --username $${DOCKER_REGISTRY_USERNAME} --password-stdin
    when:
      event: tag

  - name: push docker ${plugin}-plugin
    image: bash.exe
    commands:
      - cd ./build
      - docker-compose push plugin-${plugin}
    when:
      event: tag
